format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$java\
$python\
$rust\
$cmd_duration\
$jobs\
$status\
$character"""

[line_break]
disabled = true

# Disable the blank line at the start of the prompt
add_newline = false

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style) in "
disabled = false
show_always = true

[directory]
truncation_length = 0
truncate_to_repo = false
style = "bold purple"
read_only_style = "red"
read_only = " 🔒"

[cmd_duration]
show_milliseconds = false
format = "took [$duration](white bold) "

[status]
disabled = false
